import enum

class Register(enum.IntEnum):
    X0 = 0
    RA = 1
    SP = 2
    GP = 3
    TP = 4
    T0 = 5
    T1 = 6
    T2 = 7
    FP = 8
    S1 = 9
    A0 = 10
    A1 = 11
    A2 = 12
    A3 = 13
    A4 = 14
    A5 = 15
    A6 = 16
    A7 = 17
    S2 = 18
    S3 = 19
    S4 = 20
    S5 = 21
    S6 = 22
    S7 = 23
    S8 = 24
    S9 = 25
    S10= 26
    S11= 27
    T3 = 28
    T4 = 29
    T5 = 30
    T6 = 31

REGALLOC = [Register.T0, Register.T1, Register.T2, Register.T3, Register.T4,
            Register.T5, Register.T6, Register.S1, Register.S2, Register.S3,
            Register.S4, Register.S5, Register.S6, Register.S7, Register.S8,
            Register.S9, Register.S10, Register.S11]

class Opcode(enum.Enum):
    ADDI = enum.auto()
    SLTI = enum.auto()
    SLTIU = enum.auto()
    ANDI = enum.auto()
    ORI = enum.auto()
    XORI = enum.auto()
    SLLI = enum.auto()
    SRLI = enum.auto()
    SRAI = enum.auto()
    ADDIW = enum.auto()
    SLLIW = enum.auto()
    SRLIW = enum.auto()
    SRAIW = enum.auto()
    LUI = enum.auto()
    AUIPC = enum.auto()
    ADD = enum.auto()
    SUB = enum.auto()
    SLT = enum.auto()
    SLTU = enum.auto()
    AND = enum.auto()
    OR = enum.auto()
    XOR = enum.auto()
    SLL = enum.auto()
    SRL = enum.auto()
    SRA = enum.auto()
    ADDW = enum.auto()
    SUBW = enum.auto()
    SLLW = enum.auto()
    SRLW = enum.auto()
    SRAW = enum.auto()
    MUL = enum.auto()
    MULW = enum.auto()
    MULH = enum.auto()
    MULHU = enum.auto()
    MULHSU = enum.auto()
    DIV = enum.auto()
    DIVU = enum.auto()
    REM = enum.auto()
    REMU = enum.auto()
    DIVW = enum.auto()
    DIVUW = enum.auto()
    REMW = enum.auto()
    REMUW = enum.auto()
    BEQ = enum.auto()
    BNE = enum.auto()
    BLT = enum.auto()
    BLTU = enum.auto()
    BGE = enum.auto()
    BGEU = enum.auto()
    LD = enum.auto()
    LW = enum.auto()
    LWU = enum.auto()
    LH = enum.auto()
    LHU = enum.auto()
    LB = enum.auto()
    LBU = enum.auto()
    SD = enum.auto()
    SW = enum.auto()
    SH = enum.auto()
    SB = enum.auto()
    FENCE = enum.auto()
    ECALL = enum.auto()
    EBREAK = enum.auto()
    # Pseudoinstructions that can be translated
    # one-to-one with the above instructions
    NOP = enum.auto()   # addi x0,x0,0
    MV = enum.auto()    # addi rd,rs,0
    NOT = enum.auto()   # xori rd,rs,-1
    NEG = enum.auto()   # sub rd,x0,rs
    NEGW = enum.auto()  # subw rd,x0,rs
    SEXTW = enum.auto()
    SEQZ = enum.auto()  # sltiu rd,rs,1
    SNEZ = enum.auto()  # sltu rd,x0,rs
    SLTZ = enum.auto()  # slti rd,rs,0
    SLTZU = enum.auto() # sltiu rd,rs,0
    SGTZ = enum.auto()  # slt rd,x0,rs
    SGTZU = enum.auto() # sltu rd,x0,rs
    SGT = enum.auto()   # slt rd,rs2,rs1
    SGTU = enum.auto()  # sltu rd,rs2,rs1
    BEQZ = enum.auto()  # beq rs,x0,target
    BNEZ = enum.auto()  # bne rs,x0,target
    BLEZ = enum.auto()  # ble rs,x0,target
    BGEZ = enum.auto()  # bge rs,x0,target
    BLTZ = enum.auto()  # blt rs,x0,target
    BGTZ = enum.auto()  # bgt rs,x0,target
    BGT = enum.auto()   # blt rs2,rs1,target
    BLE = enum.auto()   # bge rs2,rs1,target
    BGTU = enum.auto()  # bltu rs2,rs1,target
    BLEU = enum.auto()  # bgeu rs2,rs1,target
    J = enum.auto()     # jal x0,imm
    JR = enum.auto()    # jalr x0,rs1,0
    JAL1 = enum.auto()
    JALR1 = enum.auto()
    RET = enum.auto()
    CALL = enum.auto()
    TAIL = enum.auto()
    FENCE0 = enum.auto()
    # Pseudoinstructions that require multiple
    # instructions to be expanded
    LA = enum.auto()
    LI = enum.auto()
    SEQ = enum.auto()
    SEQI = enum.auto()
    SNE = enum.auto()
    SNEI = enum.auto()
    SGTI = enum.auto()
    SGTIU = enum.auto()
    SLE = enum.auto()
    SLEI = enum.auto()
    SGE = enum.auto()
    SGEI = enum.auto()
    SLEU = enum.auto()
    SLEIU = enum.auto()
    SGEU = enum.auto()
    SGEIU = enum.auto()
    SLEZ = enum.auto()
    SLEZU = enum.auto()
    SGEZ = enum.auto()
    SGEZU = enum.auto()
